# ==============================================================================
# ============= DO NOT USE THESE EXAMPLE CREDENTIALS IN PRODUCTION =============
# ==============================================================================

# Test server, used only for development
kt-test:
  server-addr: server:8081

kt:
  server-addr: server:8082
  authorized-headers:
    ExampleHeader1:
      - example value one
  header-value-to-auditor-name:
    example value one: example-auditor-1

kt-query:
  server-addr: server:8080
  # at least one header-value mapping in this map will be required to be present on inbound requests with the configured value
  authorized-headers:
    ExampleHeader1:
      - example value one
  header-value-to-auditor-name:
    example value one: example-auditor-1

metrics-addr: server:8083
health-addr: server:8084

api:
  # Paste in the kt-server keys generated via `docker compose run --rm generate-keys`
  signing-key: 3536ddb5a5fdb205740aaa49314564a2181a45c44aa8af65929bf843fefc5624
  vrf-key: 712ad5ade10cfe3e784251ebf4f019e65e19e11d735ee2fae5092411935deaaa
  prefix-key: 1cfadabb9d8c6bab8f3ad846bd3bcb7afcbf7e65d85d02944f07eade76af5969
  opening-key: 2dceaf33e9491a761cb9462419256fc346da6bcd467b1071a1a0ccddc0ed951b

  # fake:
  #   count: 1
  #   interval: 10s
  distinguished: 1m

  # A map of auditor names to their encoded public keys; generated by kt-auditor
  auditors:
    example-auditor-1: e9d5a11a69b9b606b10e1e77876b544ea81acfda412c5371d65f3eabbd35ad2b

  min-search-delay: 1s
  min-monitor-delay: 1s
  jitter-percent: 10

# LevelDB
db:
  file: /db

# DynamoDB
# db:
#   table: 'kt_local'
#   parallel: 2
account-db: 'accounts' # 'mock' is treated specially
